### PR TITLE
Create 10problem.js

### PR DESCRIPTION
**Pull request by abhinaba-dash**
Hello @diwakar1593 I have added a JavaScript program for Insertion Sort. I have not updated the Readme file as it was already written JavaScript Program for Insertion Sort corresponding to number 6. So, please accept this PR and add hacktoberfest label to this PR.

### CODE REVIEW

**Comment by abhinaba-dash** [comment]
Also if you want I can change the Readme file as I can see there are some wrong program names which are mentioned in the readme file in reference to the programs that are actually written.

**Comment by diwakar1593** [comment]
@abhinaba-dash update the readme and change your file name to 08problem.js

**Comment by diwakar1593** [comment]
@abhinaba-dash Insertion sort code already submitted check the readme. Submit another problem

**Comment by abhinaba-dash** [comment]
Hello @diwakar1593 sorry for the problem from my side, i have added a new JavaScript program with the name 10problem and also updated the readme file, please accept it. #2 #1

**Comment by abhinaba-dash** [comment]
@diwakar1593 I would be very grateful if you could also please add the Hacktoberfest tag to this.

**Pull request merged**
