### PR TITLE
18problem.js

### PR DESCRIPTION
**Pull request by wshishir**
Program to find factorial of a number in js

### CODE REVIEW

**Comment by yshishir** [comment]
please add hacktoberfest label...

**Comment by diwakar1593** [comment]
@Shishirr17 Update the readme

**Comment by yshishir** [comment]
sorry sir can you please elaborate...im new to open source i didnt understand exactly what to do

**Comment by diwakar1593** [comment]
@Shishirr17 You have update my repo. readme where you have add the question name

**Pull request merged**
